### ISSUE TITLE
Check that this is not necessary

### ISSUE THREAD

**Issue by hmathieu-insat** [hmathieu-insat/PIR#39]
https://github.com/hmathieu-insat/PIR/blob/28f1ac3d1a029da98fef6950c9d58db38f220ebf/Nouveau PIR/firmware/source/main.c#L523

As you were the one to translate the USART part, do check that the Timer 1 is indeed not necessary and served no purpose besides synchronising the UART.

**Comment by Ger0th** [comment]
USART uses it's own synchronization, with an internal clock, thus Timer 1 is not required, as it is only used to synchronize the UART when a message is sent.
