### ISSUE TITLE
Make a diff of the Old code and the new code

### ISSUE THREAD

**Issue by hmathieu-insat** [hmathieu-insat/PIR#41]
- [ ] Get the new Conti code (posted yesterday) on the gitlab of Clement
- [ ] Compare every file with the Conti code we had at the beginning

Snippet of Powershell code that should probably do the trick:

`$fso = Get-ChildItem -Recurse -path _Path-of-the-former-code_`

`$fsoBU = Get-ChildItem -Recurse -path _Path-of-the-new-code_`

`Compare-Object -ReferenceObject (Get-Content $fso) -DifferenceObject (Get-Content $fsoBU)`

**Comment by Ger0th** [comment]
2012 Code is obsolete.
2020 code is the one we already had.
