### ISSUE TITLE
Port the configuration of the GPIOs to the GPIOs_config() function

### ISSUE THREAD

**Issue by hmathieu-insat** [hmathieu-insat/PIR#46]
```
    //TODO: Port the configuration of the GPIOs to the GPIOs_config() function
```

https://github.com/hmathieu-insat/PIR/blob/ac3f73af3a3ef9b103f5bf7f89e5e483f67d61ab/Nouveau PIR/firmware/source/main.c#L337

**Comment by emmanuel-pastor** [comment]
Check and do #68 before merging this branch and closing this issue
