### ISSUE TITLE
Either these functions are to be removed or they must be implemented in the source file.

### ISSUE THREAD

**Issue by hmathieu-insat** [hmathieu-insat/PIR#83]
```
		Timer4Reset(); 	// TODO: Either these functions are to be removed or they must be implemented in the source file.
```

https://github.com/hmathieu-insat/PIR/blob/4837e989a25db55b40c2afb2a8b8deb1a220ad85/Nouveau PIR/firmware/source/synchronization.c#L600

**Comment by Tsjerfell** [comment]
Closed by commit ff3cf81d83ab53ce4f4081dc8d56dfd3b1806794
